# -*- ruby -*-

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"

# Essential formulae
brew "emacs" unless OS.mac?
brew "git"
brew "gnupg"
brew "starship"
brew "zsh"
