tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"

brew "anyenv"
brew "bat"
brew "direnv"
brew "exa"
brew "fd"
brew "fzf"
brew "git"
brew "gnupg"
brew "ripgrep"
brew "starship"
brew "zip"
brew "zplug"
brew "zsh"

if OS.mac?
  brew "pinentry-mac"
end
