name: Build

on:
  push:
  pull_request:

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    steps:
      - run: |
          bash -c "$(curl -fsSL https://github.com/kou64yama/dotfiles/raw/$GITHUB_SHA/bootstrap.sh)"

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          load: true
          tags: ghcr.io/kou64yama/dotfiles:test
      - name: Test
        run: |
          docker run --rm ghcr.io/kou64yama/dotfiles:test
      - name: Build and push
        if: ${{ !github.event.issue.pull_request }}
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/kou64yama/dotfiles:latest
