name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    steps:
      - run: |
          bash -c "$(curl -fsSL https://github.com/kou64yama/dotfiles/raw/$GITHUB_SHA/bootstrap.sh)"

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build and export to Docker
        uses: docker/build-push-action@v7
        with:
          load: true
          tags: ghcr.io/kou64yama/dotfiles:latest
      - name: Build and push
        if: ${{ github.event_name == 'push' }}
        uses: docker/build-push-action@v7
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/kou64yama/dotfiles:latest
